<a href="https://colab.research.google.com/github/Nimi2607/Machine_Learning/blob/main/K_Fold_Cross_Validation_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [13]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from warnings import filterwarnings
filterwarnings('ignore')
from sklearn.datasets import load_iris
iris = load_iris()

In [14]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(iris.data, iris.target, test_size = 0.2)

In [15]:
lr = LogisticRegression()
lr.fit(X_train, y_train)
lr.score(X_test, y_test)

0.9333333333333333

In [16]:
svm = SVC()
svm.fit(X_train, y_train)
svm.score(X_test, y_test)

0.9333333333333333

In [17]:
rf = RandomForestClassifier()
rf.fit(X_train, y_train)
rf.score(X_test, y_test)

0.9333333333333333

In [18]:
def get_score(model, X_train, X_test, y_train, y_test):
    model.fit(X_train, y_train)
    return model.score(X_test, y_test)

In [19]:
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits = 10)

In [20]:
from sklearn.model_selection import cross_val_score
cross_val_score(LogisticRegression(), iris.data, iris.target)

array([0.96666667, 1.        , 0.93333333, 0.96666667, 1.        ])

In [21]:
cross_val_score(SVC(), iris.data, iris.target)

array([0.96666667, 0.96666667, 0.96666667, 0.93333333, 1.        ])

In [22]:
cross_val_score(RandomForestClassifier(), iris.data, iris.target)

array([0.96666667, 0.96666667, 0.93333333, 0.96666667, 1.        ])